on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/docker-sand
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build package
      run: |
        python setup.py sdist
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
